<a href="https://colab.research.google.com/github/akariiijima/AdversarialExample/blob/master/kerasPracticeNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [61]:
df=pd.read_csv("mnist_train.csv")
df

5  0  0.1  0.2  0.3  0.4  ...  0.612  0.613  0.614  0.615  0.616  0.617
0      0  0    0    0    0    0  ...      0      0      0      0      0      0
1      4  0    0    0    0    0  ...      0      0      0      0      0      0
2      1  0    0    0    0    0  ...      0      0      0      0      0      0
3      9  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
5      1  0    0    0    0    0  ...      0      0      0      0      0      0
6      3  0    0    0    0    0  ...      0      0      0      0      0      0
7      1  0    0    0    0    0  ...      0      0      0      0      0      0
8      4  0    0    0    0    0  ...      0      0      0      0      0      0
9      3  0    0    0    0    0  ...      0      0      0      0      0      0
10     5  0    0    0    0    0  ...      0      0      0      0      0      0
11     3  0    0    0    0    0  ...      0      0      0      0      0      0
12     6  0    0    0    0    0  ...      0      0      0      0      0      0
13     1  0    0    0    0    0  ...      0      0      0      0      0      0
14     7  0    0    0    0    0  ...      0      0      0      0      0      0
15     2  0    0    0    0    0  ...      0      0      0      0      0      0
16     8  0    0    0    0    0  ...      0      0      0      0      0      0
17     6  0    0    0    0    0  ...      0      0      0      0      0      0
18     9  0    0    0    0    0  ...      0      0      0      0      0      0
19     4  0    0    0    0    0  ...      0      0      0      0      0      0
20     0  0    0    0    0    0  ...      0      0      0      0      0      0
21     9  0    0    0    0    0  ...      0      0      0      0      0      0
22     1  0    0    0    0    0  ...      0      0      0      0      0      0
23     1  0    0    0    0    0  ...      0      0      0      0      0      0
24     2  0    0    0    0    0  ...      0      0      0      0      0      0
25     4  0    0    0    0    0  ...      0      0      0      0      0      0
26     3  0    0    0    0    0  ...      0      0      0      0      0      0
27     2  0    0    0    0    0  ...      0      0      0      0      0      0
28     7  0    0    0    0    0  ...      0      0      0      0      0      0
29     3  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
59969  2  0    0    0    0    0  ...      0      0      0      0      0      0
59970  2  0    0    0    0    0  ...      0      0      0      0      0      0
59971  0  0    0    0    0    0  ...      0      0      0      0      0      0
59972  9  0    0    0    0    0  ...      0      0      0      0      0      0
59973  2  0    0    0    0    0  ...      0      0      0      0      0      0
59974  4  0    0    0    0    0  ...      0      0      0      0      0      0
59975  6  0    0    0    0    0  ...      0      0      0      0      0      0
59976  7  0    0    0    0    0  ...      0      0      0      0      0      0
59977  3  0    0    0    0    0  ...      0      0      0      0      0      0
59978  1  0    0    0    0    0  ...      0      0      0      0      0      0
59979  3  0    0    0    0    0  ...      0      0      0      0      0      0
59980  6  0    0    0    0    0  ...      0      0      0      0      0      0
59981  6  0    0    0    0    0  ...      0      0      0      0      0      0
59982  2  0    0    0    0    0  ...      0      0      0      0      0      0
59983  1  0    0    0    0    0  ...      0      0      0      0      0      0
59984  2  0    0    0    0    0  ...      0      0      0      0      0      0
59985  6  0    0    0    0    0  ...      0      0      0      0      0      0
59986  0  0    0    0    0    0  ...      0      0      0      0      0      0
59987  7  0    0    0    0    0  ...      0      0      0

In [62]:
len(df)

59999

In [64]:
labels=df["5"].values
df.drop("5", axis=1, inplace=True)
pixels=df.values
pixels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [65]:
len(pixels[0])

784

In [66]:
pixels=pixels/255
pixels=pixels.reshape(len(df),28,28)
pixels

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [67]:
len(pixels[0][0])

28

In [72]:
df_test=pd.read_csv("mnist_test.csv")
df_test.drop("7", axis=1, inplace=True)
pixels_test=df_test.values

pixels_test=pixels_test/255
pixels_test=pixels_test.reshape(len(df_test),28,28)

pixels_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [0]:
import keras
import tensorflow as tf

In [0]:
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(280, activation=tf.nn.relu), #input distribution
    keras.layers.Dense(28, activation=tf.nn.relu),
    keras.layers.Dense(10, activation="softmax"),
])

In [75]:
model.compile(optimizer=tf.train.AdadeltaOptimizer(), loss="sparse_categorical_crossentropy", metrics=["accuracy"])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_7 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_19 (Dense)             (None, 280)               219800    
_________________________________________________________________
dense_20 (Dense)             (None, 28)                7868      
_________________________________________________________________
dense_21 (Dense)             (None, 10)                290       
Total params: 227,958
Trainable params: 227,958
Non-trainable params: 0
_________________________________________________________________


In [76]:
fit=model.fit(pixels,labels,epochs=200,validation_split=0.2)

Train on 47999 samples, validate on 12000 samples
Epoch 1/200
47999/47999 [==============================] - 7s 142us/step - loss: 2.3599 - acc: 0.0852 - val_loss: 2.3211 - val_acc: 0.0979
Epoch 2/200
47999/47999 [==============================] - 6s 127us/step - loss: 2.3030 - acc: 0.0963 - val_loss: 2.2681 - val_acc: 0.1139
Epoch 3/200
47999/47999 [==============================] - 6s 128us/step - loss: 2.2543 - acc: 0.1168 - val_loss: 2.2216 - val_acc: 0.1388
Epoch 4/200
47999/47999 [==============================] - 6s 128us/step - loss: 2.2110 - acc: 0.1456 - val_loss: 2.1790 - val_acc: 0.1742
Epoch 5/200
47999/47999 [==============================] - 6s 128us/step - loss: 2.1707 - acc: 0.1845 - val_loss: 2.1383 - val_acc: 0.2223
Epoch 6/200
47999/47999 [==============================] - 6s 127us/step - loss: 2.1315 - acc: 0.2289 - val_loss: 2.0982 - val_acc: 0.2729
Epoch 7/200
47999/47999 [==============================] - 6s 127us/step - loss: 2.0925 - acc: 0.2767 - val_loss: 2.

In [77]:
test_loss, test_acc = model.evaluate(pixels, labels)

print("Test_accuracy:", test_acc)

59999/59999 [==============================] - 3s 44us/step
Test_accuracy: 0.9036983949583481


In [0]:
data=model.predict(pixels_test)

In [79]:
number_prediction=np.array([])

for i in range(len(data)):
    number_prediction=np.append(number_prediction, np.argmax(data[i]))
    
number_prediction=number_prediction.astype(np.int64)
    
number_prediction

array([2, 1, 0, ..., 4, 5, 6])

In [81]:
df_out_view=pd.read_csv("mnist_test.csv", nrows=10)

df_out_view

7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  2  0    0    0    0    0  ...      0      0      0      0      0      0
1  1  0    0    0    0    0  ...      0      0      0      0      0      0
2  0  0    0    0    0    0  ...      0      0      0      0      0      0
3  4  0    0    0    0    0  ...      0      0      0      0      0      0
4  1  0    0    0    0    0  ...      0      0      0      0      0      0
5  4  0    0    0    0    0  ...      0      0      0      0      0      0
6  9  0    0    0    0    0  ...      0      0      0      0      0      0
7  5  0    0    0    0    0  ...      0      0      0      0      0      0
8  9  0    0    0    0    0  ...      0      0      0      0      0      0
9  0  0    0    0    0    0  ...      0      0      0      0      0      0

[10 rows x 785 columns]

In [82]:
ImgId=np.array([i+1 for i in range(len(number_prediction))])

dic={"ImageId":ImgId, "label":number_prediction}

df_out=pd.DataFrame(dic)

df_out

ImageId  label
0           1      2
1           2      1
2           3      0
3           4      4
4           5      1
5           6      4
6           7      9
7           8      6
8           9      9
9          10      0
10         11      6
11         12      9
12         13      0
13         14      1
14         15      5
15         16      9
16         17      7
17         18      3
18         19      4
19         20      9
20         21      6
21         22      6
22         23      5
23         24      4
24         25      0
25         26      7
26         27      4
27         28      0
28         29      1
29         30      3
...       ...    ...
9969     9970      3
9970     9971      2
9971     9972      4
9972     9973      9
9973     9974      4
9974     9975      2
9975     9976      6
9976     9977      4
9977     9978      1
9978     9979      7
9979     9980      3
9980     9981      6
9981     9982      6
9982     9983      0
9983     9984      1
9984     9985      2
9985     9986      8
9986     9987      4
9987     9988      5
9988     9989      6
9989     9990      7
9990     9991      8
9991     9992      9
9992     9993      0
9993     9994      1
9994     9995      2
9995     9996      3
9996     9997      4
9997     9998      5
9998     9999      6

[9999 rows x 2 columns]

In [0]:
df_out.to_csv("submissionNN.csv", index=False)