<a href="https://colab.research.google.com/github/akariiijima/AdversarialExample/blob/master/kerasPracticeCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from PIL import Image

In [36]:
df=pd.read_csv("sample_data/mnist_train_small.csv")
df

6  0  0.1  0.2  0.3  0.4  ...  0.585  0.586  0.587  0.588  0.589  0.590
0      5  0    0    0    0    0  ...      0      0      0      0      0      0
1      7  0    0    0    0    0  ...      0      0      0      0      0      0
2      9  0    0    0    0    0  ...      0      0      0      0      0      0
3      5  0    0    0    0    0  ...      0      0      0      0      0      0
4      2  0    0    0    0    0  ...      0      0      0      0      0      0
5      0  0    0    0    0    0  ...      0      0      0      0      0      0
6      6  0    0    0    0    0  ...      0      0      0      0      0      0
7      5  0    0    0    0    0  ...      0      0      0      0      0      0
8      5  0    0    0    0    0  ...      0      0      0      0      0      0
9      2  0    0    0    0    0  ...      0      0      0      0      0      0
10     7  0    0    0    0    0  ...      0      0      0      0      0      0
11     7  0    0    0    0    0  ...      0      0      0      0      0      0
12     6  0    0    0    0    0  ...      0      0      0      0      0      0
13     8  0    0    0    0    0  ...      0      0      0      0      0      0
14     9  0    0    0    0    0  ...      0      0      0      0      0      0
15     3  0    0    0    0    0  ...      0      0      0      0      0      0
16     5  0    0    0    0    0  ...      0      0      0      0      0      0
17     7  0    0    0    0    0  ...      0      0      0      0      0      0
18     6  0    0    0    0    0  ...      0      0      0      0      0      0
19     9  0    0    0    0    0  ...      0      0      0      0      0      0
20     4  0    0    0    0    0  ...      0      0      0      0      0      0
21     3  0    0    0    0    0  ...      0      0      0      0      0      0
22     4  0    0    0    0    0  ...      0      0      0      0      0      0
23     9  0    0    0    0    0  ...      0      0      0      0      0      0
24     2  0    0    0    0    0  ...      0      0      0      0      0      0
25     9  0    0    0    0    0  ...      0      0      0      0      0      0
26     1  0    0    0    0    0  ...      0      0      0      0      0      0
27     3  0    0    0    0    0  ...      0      0      0      0      0      0
28     9  0    0    0    0    0  ...      0      0      0      0      0      0
29     7  0    0    0    0    0  ...      0      0      0      0      0      0
...   .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
19969  1  0    0    0    0    0  ...      0      0      0      0      0      0
19970  9  0    0    0    0    0  ...      0      0      0      0      0      0
19971  5  0    0    0    0    0  ...      0      0      0      0      0      0
19972  5  0    0    0    0    0  ...      0      0      0      0      0      0
19973  1  0    0    0    0    0  ...      0      0      0      0      0      0
19974  6  0    0    0    0    0  ...      0      0      0      0      0      0
19975  8  0    0    0    0    0  ...      0      0      0      0      0      0
19976  4  0    0    0    0    0  ...      0      0      0      0      0      0
19977  9  0    0    0    0    0  ...      0      0      0      0      0      0
19978  3  0    0    0    0    0  ...      0      0      0      0      0      0
19979  3  0    0    0    0    0  ...      0      0      0      0      0      0
19980  4  0    0    0    0    0  ...      0      0      0      0      0      0
19981  1  0    0    0    0    0  ...      0      0      0      0      0      0
19982  2  0    0    0    0    0  ...      0      0      0      0      0      0
19983  4  0    0    0    0    0  ...      0      0      0      0      0      0
19984  6  0    0    0    0    0  ...      0      0      0      0      0      0
19985  0  0    0    0    0    0  ...      0      0      0      0      0      0
19986  3  0    0    0    0    0  ...      0      0      0      0      0      0
19987  1  0    0    0    0    0  ...      0      0      0

In [37]:
len(df)

19999

In [38]:
labels=df["6"].values
labels

array([5, 7, 9, ..., 2, 9, 5])

In [39]:
df.drop("6", axis=1, inplace=True)
pixels=df.values

pixels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
len(pixels[0])

784

In [41]:
pixels=pixels/255
pixels=pixels.reshape(len(df),28,28)

pixels

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [42]:
len(pixels[0][0])

28

In [0]:
pixels=pixels.reshape(len(df),28,28,1)

In [65]:
distribution=np.zeros((len(df), 2, 28))

for i in range(len(df)):
    for j in range(28):
        for k in range(28):
            if(pixels[i][j][k]>0):
                distribution[i][0][k]+=1.0
                distribution[i][1][j]+=1.0
    
    distribution[i][0]=distribution[i][0]/max(distribution[i][0])
    distribution[i][1]=distribution[i][1]/max(distribution[i][1])

distribution[1][0]

array([0.        , 0.        , 0.        , 0.        , 0.15384615,
       0.38461538, 0.38461538, 0.53846154, 0.53846154, 0.53846154,
       0.53846154, 0.38461538, 0.61538462, 0.69230769, 0.84615385,
       1.        , 0.76923077, 0.76923077, 0.76923077, 0.76923077,
       0.84615385, 0.69230769, 0.53846154, 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [66]:
distribution[2][0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.36842105, 0.36842105, 0.36842105, 0.36842105, 0.52631579,
       0.73684211, 1.        , 0.94736842, 0.73684211, 0.47368421,
       0.42105263, 0.31578947, 0.21052632, 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [0]:
df_test=pd.read_csv("sample_data/mnist_test.csv")
df_test.drop("7", axis=1, inplace=True)
pixels_test=df_test.values

pixels_test=pixels_test/255
pixels_test=pixels_test.reshape(len(df_test),28,28,1)


distribution_test=np.zeros((len(df_test), 2, 28))

for i in range(len(df_test)):
    for j in range(28):
        for k in range(28):
            if(pixels[i][j][k]>0):
                distribution_test[i][0][k]+=1.0
                distribution_test[i][1][j]+=1.0
    
    distribution_test[i][0]=distribution_test[i][0]/max(distribution_test[i][0])
    distribution_test[i][1]=distribution_test[i][1]/max(distribution_test[i][1])

In [52]:
import keras
import tensorflow as tf

Using TensorFlow backend.


In [53]:
input_cnn=keras.layers.Input(shape=(28, 28, 1))
model_cnn=keras.layers.Conv2D(64, (3, 3), padding="same", activation=tf.nn.relu,)(input_cnn)
model_cnn=keras.layers.Conv2D(64, (3, 3), padding="same", activation=tf.nn.relu,)(model_cnn)
model_cnn=keras.layers.MaxPooling2D(pool_size=(2,2))(model_cnn)
model_cnn=keras.layers.BatchNormalization()(model_cnn)

model_cnn=keras.layers.Conv2D(128, (3, 3), padding="same", activation=tf.nn.relu)(model_cnn)
model_cnn=keras.layers.Conv2D(128, (3, 3), padding="same", activation=tf.nn.relu,)(model_cnn)
model_cnn=keras.layers.MaxPooling2D(pool_size=(2,2))(model_cnn)
model_cnn=keras.layers.BatchNormalization()(model_cnn)
model_cnn=keras.layers.Dropout(0.1)(model_cnn)

model_cnn=keras.layers.Conv2D(512, (3, 3), padding="same", activation=tf.nn.relu)(model_cnn)
model_cnn=keras.layers.Conv2D(512, (3, 3), padding="same", activation=tf.nn.relu,)(model_cnn)
model_cnn=keras.layers.MaxPooling2D(pool_size=(2,2))(model_cnn)
model_cnn=keras.layers.BatchNormalization()(model_cnn)
model_cnn=keras.layers.Dropout(0.1)(model_cnn)

model_cnn=keras.layers.Flatten()(model_cnn)
model_cnn=keras.layers.Dense(512, activation=tf.nn.relu)(model_cnn) #input distribution
model_cnn=keras.layers.Dense(256, activation=tf.nn.relu)(model_cnn)


input_distribution=keras.layers.Input(shape=(2, 28))
model_distribution=keras.layers.Dense(128, activation=tf.nn.relu)(input_distribution)
model_distribution=keras.layers.Dense(128)(model_distribution)
model_distribution=keras.layers.Flatten()(model_distribution)
model_distribution=keras.layers.Dropout(0.1)(model_distribution)

model_out=keras.layers.concatenate([model_cnn, model_distribution])
model_out=keras.layers.Dense(256, activation=tf.nn.relu)(model_out)
model_out=keras.layers.Dense(128, activation=tf.nn.relu)(model_out)
model_out=keras.layers.Dense(10, activation="softmax")(model_out)

model=keras.models.Model(inputs=[input_cnn, input_distribution], output=model_out)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=[<tf.Tenso..., outputs=Tensor("de...)`


In [54]:
model.compile(optimizer=tf.train.AdadeltaOptimizer(), loss="sparse_categorical_crossentropy", metrics=["accuracy"])

model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 28, 28, 1)    0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 28, 28, 64)   640         input_1[0][0]                    
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 28, 28, 64)   36928       conv2d_1[0][0]                   
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 14, 14, 64)   0           conv2d_2[0][0]                   
__________________________________________________________________________________________________
batch_norm

In [63]:
len(pixels)

19999

In [64]:
len(distribution)

19999

In [67]:
len(labels)

19999

In [56]:

fit=model.fit([pixels, distribution],labels,epochs=200, batch_size=4096,validation_split=0.2)

Train on 15999 samples, validate on 4000 samples
Epoch 1/200
15999/15999 [==============================] - 5s 300us/step - loss: 1.9305 - acc: 0.4104 - val_loss: 1.8564 - val_acc: 0.5397
Epoch 2/200
15999/15999 [==============================] - 5s 300us/step - loss: 1.9163 - acc: 0.4257 - val_loss: 1.8441 - val_acc: 0.5490
Epoch 3/200
15999/15999 [==============================] - 5s 304us/step - loss: 1.9072 - acc: 0.4271 - val_loss: 1.8317 - val_acc: 0.5555
Epoch 4/200
15999/15999 [==============================] - 5s 309us/step - loss: 1.8975 - acc: 0.4407 - val_loss: 1.8191 - val_acc: 0.5642
Epoch 5/200
15999/15999 [==============================] - 5s 310us/step - loss: 1.8836 - acc: 0.4521 - val_loss: 1.8064 - val_acc: 0.5725
Epoch 6/200
15999/15999 [==============================] - 5s 310us/step - loss: 1.8747 - acc: 0.4603 - val_loss: 1.7936 - val_acc: 0.5805
Epoch 7/200
15999/15999 [==============================] - 5s 310us/step - loss: 1.8618 - acc: 0.4632 - val_loss: 1.7

In [57]:
test_loss, test_acc = model.evaluate([pixels, distribution], labels)

print("Test_accuracy:", test_acc)

19999/19999 [==============================] - 3s 164us/step
Test_accuracy: 0.9343967197942664


In [58]:
data=model.predict([pixels_test, distribution_test])
number_prediction=np.array([])

for i in range(len(data)):
    number_prediction=np.append(number_prediction, np.argmax(data[i]))
    
number_prediction=number_prediction.astype(np.int64)
    
number_prediction

array([2, 1, 0, ..., 4, 5, 6])

In [59]:
df_out_view=pd.read_csv("sample_data/mnist_test.csv", nrows=10)

df_out_view


7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0  2  0    0    0    0    0  ...      0      0      0      0      0      0
1  1  0    0    0    0    0  ...      0      0      0      0      0      0
2  0  0    0    0    0    0  ...      0      0      0      0      0      0
3  4  0    0    0    0    0  ...      0      0      0      0      0      0
4  1  0    0    0    0    0  ...      0      0      0      0      0      0
5  4  0    0    0    0    0  ...      0      0      0      0      0      0
6  9  0    0    0    0    0  ...      0      0      0      0      0      0
7  5  0    0    0    0    0  ...      0      0      0      0      0      0
8  9  0    0    0    0    0  ...      0      0      0      0      0      0
9  0  0    0    0    0    0  ...      0      0      0      0      0      0

[10 rows x 785 columns]

In [60]:
ImgId=np.array([i+1 for i in range(len(number_prediction))])

dic={"ImageId":ImgId, "label":number_prediction}

df_out=pd.DataFrame(dic)

df_out

ImageId  label
0           1      2
1           2      1
2           3      0
3           4      4
4           5      1
5           6      4
6           7      9
7           8      6
8           9      9
9          10      0
10         11      6
11         12      9
12         13      0
13         14      1
14         15      5
15         16      9
16         17      7
17         18      3
18         19      4
19         20      9
20         21      6
21         22      6
22         23      5
23         24      4
24         25      0
25         26      7
26         27      4
27         28      0
28         29      1
29         30      3
...       ...    ...
9969     9970      5
9970     9971      2
9971     9972      4
9972     9973      9
9973     9974      4
9974     9975      8
9975     9976      6
9976     9977      4
9977     9978      1
9978     9979      7
9979     9980      2
9980     9981      6
9981     9982      6
9982     9983      0
9983     9984      1
9984     9985      2
9985     9986      3
9986     9987      4
9987     9988      5
9988     9989      6
9989     9990      7
9990     9991      8
9991     9992      9
9992     9993      0
9993     9994      1
9994     9995      2
9995     9996      3
9996     9997      4
9997     9998      5
9998     9999      6

[9999 rows x 2 columns]

In [0]:
df_out.to_csv("submission.csv", index=False)

In [0]:
df_test=pd.read_csv("sample_data/mnist_test.csv")
df_test